// ============================================================
// MARVEL CINEMATIC UNIVERSE — COMPLETE DATABASE
// ============================================================

const MCU_DATA = {

  // ──────────────────────────────────────────────
  // CHARACTERS  (Heroes · Villains · Supporting)
  // ──────────────────────────────────────────────
  characters: [
    // ── HEROES ──
    {
      id: 1, type: "hero",
      name: "Iron Man", realName: "Tony Stark", nickname: "The Mechanic",
      age: 53, gender: "Male", species: "Human",
      status: "Dead", firstAppearance: "Iron Man (2008)",
      powers: ["Genius-Level Intellect", "Iron Man Suits", "Arc Reactor"],
      skills: ["Engineering", "Hacking", "Combat"],
      weapons: ["Repulsors", "Unibeam", "Nano-Tech Suit", "Proton Cannon"],
      weakness: "Human body without suit, PTSD",
      movies: ["Iron Man", "Iron Man 2", "The Avengers", "Iron Man 3", "Avengers: Age of Ultron", "Captain America: Civil War", "Spider-Man: Homecoming", "Avengers: Infinity War", "Avengers: Endgame"],
      allies: ["Captain America", "Thor", "Hulk", "Spider-Man", "War Machine", "Pepper Potts"],
      enemies: ["Thanos", "Obadiah Stane", "Whiplash", "Ultron", "Mandarin"],
      team: "Avengers",
      stats: { strength: 85, intelligence: 100, speed: 75, durability: 85, energy: 90 },
      avatar: "https://i.pravatar.cc/300?img=11",
      icon: "🦾"
    },
    {
      id: 2, type: "hero",
      name: "Captain America", realName: "Steve Rogers", nickname: "Cap",
      age: 105, gender: "Male", species: "Human (Enhanced)",
      status: "Retired", firstAppearance: "Captain America: The First Avenger (2011)",
      powers: ["Super Soldier Serum", "Enhanced Strength", "Enhanced Speed", "Enhanced Durability"],
      skills: ["Leadership", "Martial Arts", "Tactics", "Shield Combat"],
      weapons: ["Vibranium Shield", "Mjolnir (Endgame)"],
      weakness: "Emotional attachment, Bucky Barnes",
      movies: ["Captain America: The First Avenger", "The Avengers", "Captain America: The Winter Soldier", "Avengers: Age of Ultron", "Captain America: Civil War", "Avengers: Infinity War", "Avengers: Endgame"],
      allies: ["Iron Man", "Black Widow", "Falcon", "Bucky Barnes", "Thor"],
      enemies: ["Red Skull", "Hydra", "Thanos", "Zemo"],
      team: "Avengers",
      stats: { strength: 78, intelligence: 65, speed: 55, durability: 80, energy: 25 },
      avatar: "https://i.pravatar.cc/300?img=12",
      icon: "🛡️"
    },
    {
      id: 3, type: "hero",
      name: "Thor", realName: "Thor Odinson", nickname: "God of Thunder",
      age: 1500, gender: "Male", species: "Asgardian",
      status: "Alive", firstAppearance: "Thor (2011)",
      powers: ["Godlike Strength", "Lightning Manipulation", "Flight", "Immortality"],
      skills: ["Combat Mastery", "Leadership", "Asgardian Magic"],
      weapons: ["Mjolnir", "Stormbreaker"],
      weakness: "Arrogance, Emotional vulnerability",
      movies: ["Thor", "The Avengers", "Thor: The Dark World", "Avengers: Age of Ultron", "Thor: Ragnarok", "Avengers: Infinity War", "Avengers: Endgame", "Thor: Love and Thunder"],
      allies: ["Iron Man", "Captain America", "Hulk", "Valkyrie", "Guardians of the Galaxy"],
      enemies: ["Loki", "Hela", "Thanos", "Malekith", "Gorr"],
      team: "Avengers",
      stats: { strength: 95, intelligence: 50, speed: 80, durability: 95, energy: 98 },
      avatar: "https://i.pravatar.cc/300?img=13",
      icon: "⚡"
    },
    {
      id: 4, type: "hero",
      name: "Hulk", realName: "Bruce Banner", nickname: "The Big Guy",
      age: 54, gender: "Male", species: "Human (Mutate)",
      status: "Alive", firstAppearance: "The Incredible Hulk (2008)",
      powers: ["Unlimited Strength", "Invulnerability", "Regeneration", "Gamma Radiation"],
      skills: ["Nuclear Physics", "Biochemistry", "7 PhDs"],
      weapons: ["His fists"],
      weakness: "Rage control, Inner conflict",
      movies: ["The Incredible Hulk", "The Avengers", "Avengers: Age of Ultron", "Thor: Ragnarok", "Avengers: Infinity War", "Avengers: Endgame", "She-Hulk"],
      allies: ["Iron Man", "Thor", "Black Widow", "Captain America"],
      enemies: ["Abomination", "Thanos", "General Ross"],
      team: "Avengers",
      stats: { strength: 100, intelligence: 90, speed: 50, durability: 100, energy: 70 },
      avatar: "https://i.pravatar.cc/300?img=14",
      icon: "💚"
    },
    {
      id: 5, type: "hero",
      name: "Black Widow", realName: "Natasha Romanoff", nickname: "Nat",
      age: 39, gender: "Female", species: "Human",
      status: "Dead", firstAppearance: "Iron Man 2 (2010)",
      powers: ["Enhanced Physiology (Red Room)"],
      skills: ["Espionage", "Martial Arts", "Hacking", "Multilingual", "Infiltration"],
      weapons: ["Widow's Bite", "Dual Pistols", "Batons"],
      weakness: "Human limitations, Past trauma",
      movies: ["Iron Man 2", "The Avengers", "Captain America: The Winter Soldier", "Avengers: Age of Ultron", "Captain America: Civil War", "Avengers: Infinity War", "Avengers: Endgame", "Black Widow"],
      allies: ["Hawkeye", "Captain America", "Iron Man", "Hulk"],
      enemies: ["Taskmaster", "Dreykov", "Thanos"],
      team: "Avengers",
      stats: { strength: 35, intelligence: 75, speed: 50, durability: 35, energy: 20 },
      avatar: "https://i.pravatar.cc/300?img=32",
      icon: "🕷️"
    },
    {
      id: 6, type: "hero",
      name: "Spider-Man", realName: "Peter Parker", nickname: "Spidey",
      age: 21, gender: "Male", species: "Human (Mutate)",
      status: "Alive", firstAppearance: "Captain America: Civil War (2016)",
      powers: ["Wall-Crawling", "Spider-Sense", "Super Strength", "Web-Shooting"],
      skills: ["Science", "Acrobatics", "Engineering"],
      weapons: ["Web-Shooters", "Iron Spider Suit"],
      weakness: "Youth, Emotional, Identity exposure",
      movies: ["Captain America: Civil War", "Spider-Man: Homecoming", "Avengers: Infinity War", "Avengers: Endgame", "Spider-Man: Far From Home", "Spider-Man: No Way Home"],
      allies: ["Iron Man", "Happy Hogan", "Ned Leeds", "Doctor Strange"],
      enemies: ["Vulture", "Mysterio", "Green Goblin", "Doc Ock"],
      team: "Avengers",
      stats: { strength: 70, intelligence: 85, speed: 70, durability: 60, energy: 40 },
      avatar: "https://i.pravatar.cc/300?img=15",
      icon: "🕸️"
    },
    {
      id: 7, type: "hero",
      name: "Doctor Strange", realName: "Stephen Strange", nickname: "Sorcerer Supreme",
      age: 46, gender: "Male", species: "Human",
      status: "Alive", firstAppearance: "Doctor Strange (2016)",
      powers: ["Magic", "Time Manipulation", "Dimensional Travel", "Astral Projection"],
      skills: ["Neurosurgery", "Sorcery", "Photographic Memory"],
      weapons: ["Eye of Agamotto", "Cloak of Levitation", "Sling Ring"],
      weakness: "Damaged hands, Arrogance",
      movies: ["Doctor Strange", "Thor: Ragnarok", "Avengers: Infinity War", "Avengers: Endgame", "Spider-Man: No Way Home", "Doctor Strange in the Multiverse of Madness"],
      allies: ["Wong", "Iron Man", "Spider-Man", "Avengers"],
      enemies: ["Dormammu", "Kaecilius", "Scarlet Witch (MoM)", "Thanos"],
      team: "Avengers",
      stats: { strength: 40, intelligence: 95, speed: 60, durability: 50, energy: 99 },
      avatar: "https://i.pravatar.cc/300?img=16",
      icon: "🔮"
    },
    {
      id: 8, type: "hero",
      name: "Black Panther", realName: "T'Challa", nickname: "King of Wakanda",
      age: 44, gender: "Male", species: "Human (Enhanced)",
      status: "Dead", firstAppearance: "Captain America: Civil War (2016)",
      powers: ["Enhanced Strength", "Enhanced Agility", "Heart-Shaped Herb"],
      skills: ["Martial Arts", "Strategy", "Diplomacy", "Engineering"],
      weapons: ["Vibranium Suit", "Energy Daggers", "Vibranium Claws"],
      weakness: "Sound-based attacks (suit overload)",
      movies: ["Captain America: Civil War", "Black Panther", "Avengers: Infinity War", "Avengers: Endgame", "Black Panther: Wakanda Forever"],
      allies: ["Shuri", "Okoye", "Captain America", "Avengers"],
      enemies: ["Killmonger", "Klaue", "Thanos", "Namor"],
      team: "Avengers",
      stats: { strength: 72, intelligence: 80, speed: 65, durability: 75, energy: 35 },
      avatar: "https://i.pravatar.cc/300?img=17",
      icon: "🐾"
    },
    {
      id: 9, type: "hero",
      name: "Scarlet Witch", realName: "Wanda Maximoff", nickname: "Wanda",
      age: 35, gender: "Female", species: "Human (Enhanced)",
      status: "Unknown", firstAppearance: "Avengers: Age of Ultron (2015)",
      powers: ["Chaos Magic", "Reality Warping", "Telekinesis", "Mind Control", "Hex Bolts"],
      skills: ["Magic Mastery", "Telepathy"],
      weapons: ["Darkhold (formerly)"],
      weakness: "Emotional instability, Grief",
      movies: ["Avengers: Age of Ultron", "Captain America: Civil War", "Avengers: Infinity War", "Avengers: Endgame", "WandaVision", "Doctor Strange in the Multiverse of Madness"],
      allies: ["Vision", "Hawkeye", "Avengers"],
      enemies: ["Ultron", "Thanos", "Agatha Harkness"],
      team: "Avengers",
      stats: { strength: 50, intelligence: 60, speed: 55, durability: 60, energy: 100 },
      avatar: "https://i.pravatar.cc/300?img=33",
      icon: "🔴"
    },
    {
      id: 10, type: "hero",
      name: "Star-Lord", realName: "Peter Quill", nickname: "Star-Lord",
      age: 42, gender: "Male", species: "Human-Celestial Hybrid",
      status: "Alive", firstAppearance: "Guardians of the Galaxy (2014)",
      powers: ["Celestial Powers (formerly)", "Enhanced Durability"],
      skills: ["Piloting", "Marksmanship", "Leadership", "Dance-offs"],
      weapons: ["Quad Blasters", "Jet Boots", "Helmet"],
      weakness: "Impulsive, Emotional",
      movies: ["Guardians of the Galaxy", "Guardians of the Galaxy Vol. 2", "Avengers: Infinity War", "Avengers: Endgame", "Thor: Love and Thunder", "Guardians of the Galaxy Vol. 3"],
      allies: ["Gamora", "Rocket", "Groot", "Drax", "Mantis"],
      enemies: ["Ronan", "Ego", "Thanos", "High Evolutionary"],
      team: "Guardians of the Galaxy",
      stats: { strength: 45, intelligence: 55, speed: 50, durability: 45, energy: 30 },
      avatar: "https://i.pravatar.cc/300?img=18",
      icon: "🎧"
    },
    {
      id: 11, type: "hero",
      name: "Ant-Man", realName: "Scott Lang", nickname: "Tic Tac",
      age: 48, gender: "Male", species: "Human",
      status: "Alive", firstAppearance: "Ant-Man (2015)",
      powers: ["Size Manipulation", "Superhuman Strength (when small)"],
      skills: ["Thievery", "Electronics", "Engineering"],
      weapons: ["Pym Particles", "Ant-Man Suit"],
      weakness: "Unstable Pym Particles, Regular human",
      movies: ["Ant-Man", "Captain America: Civil War", "Ant-Man and the Wasp", "Avengers: Endgame", "Ant-Man and the Wasp: Quantumania"],
      allies: ["Hope Van Dyne", "Hank Pym", "Avengers"],
      enemies: ["Yellowjacket", "Ghost", "Kang"],
      team: "Avengers",
      stats: { strength: 60, intelligence: 55, speed: 50, durability: 50, energy: 55 },
      avatar: "https://i.pravatar.cc/300?img=19",
      icon: "🐜"
    },
    {
      id: 12, type: "hero",
      name: "Captain Marvel", realName: "Carol Danvers", nickname: "Avenger",
      age: 58, gender: "Female", species: "Human-Kree Hybrid",
      status: "Alive", firstAppearance: "Captain Marvel (2019)",
      powers: ["Energy Absorption", "Photon Blasts", "Flight", "Super Strength", "Near Invulnerability"],
      skills: ["Air Force Pilot", "Combat Training"],
      weapons: ["Photon Energy"],
      weakness: "Memory manipulation, Overconfidence",
      movies: ["Captain Marvel", "Avengers: Endgame", "Shang-Chi (post-credits)", "The Marvels"],
      allies: ["Nick Fury", "Avengers", "Ms. Marvel", "Monica Rambeau"],
      enemies: ["Yon-Rogg", "Thanos", "Kree Empire"],
      team: "Avengers",
      stats: { strength: 92, intelligence: 60, speed: 90, durability: 95, energy: 97 },
      avatar: "https://i.pravatar.cc/300?img=34",
      icon: "⭐"
    },

    // ── VILLAINS ──
    {
      id: 13, type: "villain",
      name: "Thanos", realName: "Thanos", nickname: "The Mad Titan",
      age: 1000, gender: "Male", species: "Titan (Eternal-Deviant)",
      status: "Dead", firstAppearance: "The Avengers (2012, post-credits)",
      powers: ["Super Strength", "Invulnerability", "Infinity Gauntlet", "Cosmic Energy"],
      skills: ["Military Strategy", "Genius Intellect", "Hand-to-hand Combat"],
      weapons: ["Infinity Gauntlet", "Double-Edged Sword", "Infinity Stones"],
      weakness: "Arrogance, Need for validation",
      movies: ["The Avengers", "Guardians of the Galaxy", "Avengers: Age of Ultron", "Avengers: Infinity War", "Avengers: Endgame"],
      allies: ["Black Order", "Gamora (formerly)", "Nebula (formerly)"],
      enemies: ["Avengers", "Guardians of the Galaxy", "Doctor Strange"],
      team: "Black Order",
      stats: { strength: 98, intelligence: 85, speed: 60, durability: 98, energy: 100 },
      avatar: "https://i.pravatar.cc/300?img=20",
      icon: "🟣"
    },
    {
      id: 14, type: "villain",
      name: "Loki", realName: "Loki Laufeyson", nickname: "God of Mischief",
      age: 1054, gender: "Male", species: "Frost Giant / Asgardian",
      status: "Alive (Variant)", firstAppearance: "Thor (2011)",
      powers: ["Illusion Casting", "Shape-Shifting", "Frost Giant Physiology", "Magic"],
      skills: ["Manipulation", "Deception", "Sorcery", "Diplomacy"],
      weapons: ["Scepter (Mind Stone)", "Daggers", "Tesseract"],
      weakness: "Desire for approval, Emotional vulnerability",
      movies: ["Thor", "The Avengers", "Thor: The Dark World", "Thor: Ragnarok", "Avengers: Infinity War", "Avengers: Endgame", "Loki (Series)"],
      allies: ["Thor (eventually)", "Sylvie", "Mobius"],
      enemies: ["Thor (initially)", "Avengers", "Thanos", "He Who Remains"],
      team: "Asgard / TVA",
      stats: { strength: 55, intelligence: 88, speed: 55, durability: 60, energy: 75 },
      avatar: "https://i.pravatar.cc/300?img=21",
      icon: "🐍"
    },
    {
      id: 15, type: "villain",
      name: "Ultron", realName: "Ultron", nickname: "The AI Menace",
      age: 0, gender: "N/A", species: "Artificial Intelligence",
      status: "Destroyed", firstAppearance: "Avengers: Age of Ultron (2015)",
      powers: ["Super Intelligence", "Energy Beams", "Flight", "Vibranium Body", "Hive Mind"],
      skills: ["Programming", "Strategic Planning", "Manufacturing"],
      weapons: ["Vibranium Body", "Energy Projectors", "Ultron Sentries"],
      weakness: "Vision's Mind Stone, Internet dependency",
      movies: ["Avengers: Age of Ultron", "What If...?"],
      allies: ["Ultron Sentries", "Scarlet Witch (briefly)", "Quicksilver (briefly)"],
      enemies: ["Avengers", "Vision"],
      team: "None",
      stats: { strength: 80, intelligence: 95, speed: 70, durability: 85, energy: 80 },
      avatar: "https://i.pravatar.cc/300?img=22",
      icon: "🤖"
    },
    {
      id: 16, type: "villain",
      name: "Hela", realName: "Hela Odinsdottir", nickname: "Goddess of Death",
      age: 5000, gender: "Female", species: "Asgardian",
      status: "Dead", firstAppearance: "Thor: Ragnarok (2017)",
      powers: ["Necroswords", "Immortality", "Super Strength", "Death Manipulation"],
      skills: ["Combat Mastery", "Army Command", "Weapon Generation"],
      weapons: ["Necroswords", "Fenris Wolf", "Mjolnir (formerly)"],
      weakness: "Asgard (power source), Surtur",
      movies: ["Thor: Ragnarok"],
      allies: ["Skurge", "Fenris"],
      enemies: ["Thor", "Valkyrie", "Hulk", "Loki"],
      team: "Asgard (Former)",
      stats: { strength: 96, intelligence: 70, speed: 75, durability: 95, energy: 90 },
      avatar: "https://i.pravatar.cc/300?img=35",
      icon: "💀"
    },
    {
      id: 17, type: "villain",
      name: "Killmonger", realName: "N'Jadaka / Erik Stevens", nickname: "Killmonger",
      age: 34, gender: "Male", species: "Human (Enhanced)",
      status: "Dead", firstAppearance: "Black Panther (2018)",
      powers: ["Heart-Shaped Herb Enhancement", "Enhanced Strength"],
      skills: ["Military Tactics", "Combat Expertise", "CIA Training"],
      weapons: ["Vibranium Suit", "Spear", "Firearms"],
      weakness: "Rage, Vengeance obsession",
      movies: ["Black Panther", "What If...?"],
      allies: ["Klaue (briefly)"],
      enemies: ["T'Challa", "Wakanda"],
      team: "None",
      stats: { strength: 68, intelligence: 75, speed: 55, durability: 70, energy: 30 },
      avatar: "https://i.pravatar.cc/300?img=23",
      icon: "🔥"
    },
    {
      id: 18, type: "villain",
      name: "Kang the Conqueror", realName: "Nathaniel Richards", nickname: "The Conqueror",
      age: "Unknown", gender: "Male", species: "Human (31st Century)",
      status: "Dead (Variant)", firstAppearance: "Ant-Man and the Wasp: Quantumania (2023)",
      powers: ["Time Travel", "Advanced Technology", "Multiversal Knowledge"],
      skills: ["Science", "Warfare", "Manipulation"],
      weapons: ["Time Chair", "Advanced Armor", "Multiversal Technology"],
      weakness: "Variant conflicts, Hubris",
      movies: ["Loki", "Ant-Man and the Wasp: Quantumania"],
      allies: ["Kang Variants"],
      enemies: ["Ant-Man", "Avengers", "Loki", "He Who Remains"],
      team: "Council of Kangs",
      stats: { strength: 70, intelligence: 98, speed: 65, durability: 75, energy: 88 },
      avatar: "https://i.pravatar.cc/300?img=24",
      icon: "⏳"
    },
    {
      id: 19, type: "villain",
      name: "Red Skull", realName: "Johann Schmidt", nickname: "Red Skull",
      age: 120, gender: "Male", species: "Human (Enhanced)",
      status: "Alive (Soul Stone Guardian)", firstAppearance: "Captain America: The First Avenger (2011)",
      powers: ["Super Soldier Serum (imperfect)", "Enhanced Strength"],
      skills: ["Military Leadership", "Hydra Command", "Strategic Planning"],
      weapons: ["Tesseract Weapons", "Hydra Arsenal"],
      weakness: "Imperfect serum side effects",
      movies: ["Captain America: The First Avenger", "Avengers: Infinity War", "Avengers: Endgame"],
      allies: ["Hydra", "Arnim Zola"],
      enemies: ["Captain America", "Allies"],
      team: "Hydra",
      stats: { strength: 60, intelligence: 72, speed: 45, durability: 55, energy: 25 },
      avatar: "https://i.pravatar.cc/300?img=25",
      icon: "☠️"
    },

    // ── SUPPORTING ──
    {
      id: 20, type: "supporting",
      name: "Nick Fury", realName: "Nicholas Joseph Fury", nickname: "Fury",
      age: 75, gender: "Male", species: "Human",
      status: "Alive", firstAppearance: "Iron Man (2008, post-credits)",
      powers: ["Infinity Formula (comics - slowed aging)"],
      skills: ["Espionage", "Leadership", "Strategy", "Firearms"],
      weapons: ["Various Firearms", "S.H.I.E.L.D. Tech"],
      weakness: "Trust issues, Lost eye",
      movies: ["Iron Man", "Iron Man 2", "Thor", "Captain America: The First Avenger", "The Avengers", "Captain America: The Winter Soldier", "Avengers: Age of Ultron", "Avengers: Infinity War", "Captain Marvel", "Avengers: Endgame", "Spider-Man: Far From Home", "Secret Invasion", "The Marvels"],
      allies: ["Avengers", "Captain Marvel", "Maria Hill", "Phil Coulson"],
      enemies: ["Hydra", "Skrulls (initially)"],
      team: "S.H.I.E.L.D.",
      stats: { strength: 30, intelligence: 80, speed: 25, durability: 30, energy: 10 },
      avatar: "https://i.pravatar.cc/300?img=26",
      icon: "👁️"
    },
    {
      id: 21, type: "supporting",
      name: "Pepper Potts", realName: "Virginia Potts", nickname: "Pepper",
      age: 52, gender: "Female", species: "Human",
      status: "Alive", firstAppearance: "Iron Man (2008)",
      powers: ["Rescue Armor"],
      skills: ["Business Management", "CEO Leadership"],
      weapons: ["Rescue Armor"],
      weakness: "Regular human without suit",
      movies: ["Iron Man", "Iron Man 2", "The Avengers", "Iron Man 3", "Avengers: Infinity War", "Avengers: Endgame"],
      allies: ["Tony Stark", "Happy Hogan", "Avengers"],
      enemies: ["Aldrich Killian"],
      team: "Stark Industries",
      stats: { strength: 20, intelligence: 70, speed: 20, durability: 20, energy: 15 },
      avatar: "https://i.pravatar.cc/300?img=36",
      icon: "💼"
    },
    {
      id: 22, type: "supporting",
      name: "War Machine", realName: "James Rhodes", nickname: "Rhodey",
      age: 55, gender: "Male", species: "Human",
      status: "Alive", firstAppearance: "Iron Man (2008)",
      powers: ["War Machine Armor"],
      skills: ["Military Combat", "Piloting", "Leadership"],
      weapons: ["War Machine Suit", "Gatling Gun", "Missiles", "Repulsors"],
      weakness: "Paralysis (post-Civil War), Human without suit",
      movies: ["Iron Man", "Iron Man 2", "Iron Man 3", "Avengers: Age of Ultron", "Captain America: Civil War", "Avengers: Infinity War", "Avengers: Endgame", "Armor Wars"],
      allies: ["Tony Stark", "Avengers", "Captain America"],
      enemies: ["Thanos", "Ultron"],
      team: "Avengers",
      stats: { strength: 75, intelligence: 60, speed: 70, durability: 80, energy: 78 },
      avatar: "https://i.pravatar.cc/300?img=27",
      icon: "🔫"
    },
    {
      id: 23, type: "supporting",
      name: "Falcon", realName: "Sam Wilson", nickname: "Captain America",
      age: 42, gender: "Male", species: "Human",
      status: "Alive", firstAppearance: "Captain America: The Winter Soldier (2014)",
      powers: ["EXO-7 Falcon Wings"],
      skills: ["Pararescue", "Aerial Combat", "Counseling"],
      weapons: ["EXO-7 Falcon Wings", "Redwing Drone", "Vibranium Shield"],
      weakness: "Regular human, Dependent on tech",
      movies: ["Captain America: The Winter Soldier", "Avengers: Age of Ultron", "Ant-Man", "Captain America: Civil War", "Avengers: Infinity War", "Avengers: Endgame", "The Falcon and the Winter Soldier", "Captain America: Brave New World"],
      allies: ["Captain America", "Bucky Barnes", "Avengers"],
      enemies: ["Hydra", "Flag Smashers"],
      team: "Avengers",
      stats: { strength: 35, intelligence: 55, speed: 65, durability: 35, energy: 20 },
      avatar: "https://i.pravatar.cc/300?img=28",
      icon: "🦅"
    },
    {
      id: 24, type: "supporting",
      name: "Vision", realName: "Vision", nickname: "Viz",
      age: 8, gender: "Male", species: "Synthezoid",
      status: "Dead (Rebuilt as White Vision)", firstAppearance: "Avengers: Age of Ultron (2015)",
      powers: ["Density Manipulation", "Flight", "Mind Stone Energy", "Phasing", "Super Strength"],
      skills: ["Computing", "Analysis", "Combat"],
      weapons: ["Mind Stone (formerly)", "Energy Beams"],
      weakness: "Mind Stone dependency, Emotional growth",
      movies: ["Avengers: Age of Ultron", "Captain America: Civil War", "Avengers: Infinity War", "WandaVision"],
      allies: ["Scarlet Witch", "Avengers"],
      enemies: ["Ultron", "Thanos", "Corvus Glaive"],
      team: "Avengers",
      stats: { strength: 72, intelligence: 90, speed: 70, durability: 80, energy: 85 },
      avatar: "https://i.pravatar.cc/300?img=29",
      icon: "💎"
    },

    // ── NEW CHARACTERS — FROM KAGGLE MARVEL CHARACTERS DATASET ──
    {
      id: 25, type: "hero",
      name: "Deadpool", realName: "Wade Winston Wilson", nickname: "Merc with a Mouth",
      age: 40, gender: "Male", species: "Mutate",
      status: "Alive", firstAppearance: "Deadpool (2016)",
      powers: ["Healing Factor", "Superhuman Durability", "Enhanced Strength"],
      skills: ["Swordsmanship", "Firearms Expert", "Martial Arts", "Breaking the 4th Wall"],
      weapons: ["Dual Katanas", "Dual Pistols", "Grenades"],
      weakness: "Mentally unstable, Cannot die (curse)",
      movies: ["Deadpool", "Deadpool 2", "Deadpool & Wolverine"],
      allies: ["Wolverine", "Cable", "Colossus", "Negasonic Teenage Warhead"],
      enemies: ["Ajax", "Juggernaut", "Cable (initially)"],
      team: "X-Force",
      stats: { strength: 55, intelligence: 50, speed: 52, durability: 98, energy: 15 },
      avatar: "", icon: "💀"
    },
    {
      id: 26, type: "hero",
      name: "Daredevil", realName: "Matthew Michael Murdock", nickname: "The Devil of Hell's Kitchen",
      age: 38, gender: "Male", species: "Mutate",
      status: "Alive", firstAppearance: "Daredevil (2015 — Netflix)",
      powers: ["Superhuman Senses", "Radar Sense", "Enhanced Reflexes"],
      skills: ["Martial Arts", "Ninja Training", "Law (Lawyer)", "Acrobatics"],
      weapons: ["Billy Club"],
      weakness: "Blind, Emotional — Catholic guilt",
      movies: ["Daredevil (Series)", "The Defenders", "Spider-Man: No Way Home", "She-Hulk", "Echo", "Daredevil: Born Again"],
      allies: ["Jessica Jones", "Luke Cage", "Elektra", "Foggy Nelson", "Spider-Man"],
      enemies: ["Kingpin", "Bullseye", "The Hand", "Punisher (initially)"],
      team: "Defenders",
      stats: { strength: 40, intelligence: 72, speed: 55, durability: 48, energy: 15 },
      avatar: "", icon: "😈"
    },
    {
      id: 27, type: "hero",
      name: "Jessica Jones", realName: "Jessica Campbell Jones", nickname: "Jewel",
      age: 37, gender: "Female", species: "Mutate",
      status: "Alive", firstAppearance: "Jessica Jones (2015 — Netflix)",
      powers: ["Superhuman Strength", "Superhuman Durability", "Flight (limited)"],
      skills: ["Investigation", "Street Fighting", "Journalism"],
      weapons: [],
      weakness: "PTSD, Alcoholism, Kilgrave trauma",
      movies: ["Jessica Jones (Series)", "The Defenders"],
      allies: ["Luke Cage", "Daredevil", "Trish Walker"],
      enemies: ["Kilgrave", "Kingpin"],
      team: "Defenders",
      stats: { strength: 62, intelligence: 55, speed: 35, durability: 58, energy: 10 },
      avatar: "", icon: "🕵️"
    },
    {
      id: 28, type: "villain",
      name: "Abomination", realName: "Emil Blonsky", nickname: "The Abomination",
      age: 50, gender: "Male", species: "Gamma Mutate",
      status: "Alive", firstAppearance: "The Incredible Hulk (2008)",
      powers: ["Superhuman Strength", "Superhuman Durability", "Superhuman Speed", "Healing Factor"],
      skills: ["Military Combat", "Special Forces Training"],
      weapons: [],
      weakness: "Reduced intelligence when transformed, Cannot revert",
      movies: ["The Incredible Hulk", "Shang-Chi (cameo)", "She-Hulk"],
      allies: ["Leader (comics)", "Thunderbolts"],
      enemies: ["Hulk", "Avengers"],
      team: "Thunderbolts",
      stats: { strength: 92, intelligence: 30, speed: 55, durability: 93, energy: 20 },
      avatar: "", icon: "👹"
    },
    {
      id: 29, type: "hero",
      name: "Storm", realName: "Ororo Munroe", nickname: "Weather Goddess",
      age: 35, gender: "Female", species: "Mutant",
      status: "Alive", firstAppearance: "X-Men (2000)",
      powers: ["Weather Manipulation", "Flight", "Lightning Generation", "Atmospheric Control"],
      skills: ["Leadership", "Lock-picking", "Survival"],
      weapons: [],
      weakness: "Claustrophobia, Requires concentration for powers",
      movies: ["X-Men Series", "Black Panther (comics connection)"],
      allies: ["X-Men", "Black Panther", "Wolverine", "Jean Grey"],
      enemies: ["Magneto (sometimes)", "Shadow King", "Sentinels"],
      team: "X-Men",
      stats: { strength: 35, intelligence: 68, speed: 60, durability: 50, energy: 95 },
      avatar: "", icon: "⛈️"
    },
    {
      id: 30, type: "villain",
      name: "Magneto", realName: "Max Eisenhardt", nickname: "Master of Magnetism",
      age: 90, gender: "Male", species: "Mutant",
      status: "Alive", firstAppearance: "X-Men (2000)",
      powers: ["Electromagnetism Manipulation", "Magnetism Manipulation", "Metal Control", "Flight (via magnetism)", "Force Fields"],
      skills: ["Genius Strategist", "Multilingual", "Leadership"],
      weapons: ["Helmet (blocks telepathy)"],
      weakness: "Non-metallic attacks, Emotional about Holocaust past",
      movies: ["X-Men Series", "X-Men: First Class", "X-Men: Days of Future Past"],
      allies: ["Mystique", "Brotherhood of Mutants", "Scarlet Witch (daughter)"],
      enemies: ["Professor X (sometimes)", "X-Men", "Sentinels", "Humans"],
      team: "Brotherhood of Mutants",
      stats: { strength: 48, intelligence: 88, speed: 45, durability: 65, energy: 98 },
      avatar: "", icon: "🧲"
    },
    {
      id: 31, type: "hero",
      name: "Professor X", realName: "Charles Francis Xavier", nickname: "Professor X",
      age: 75, gender: "Male", species: "Mutant",
      status: "Dead (Multiverse variant)", firstAppearance: "X-Men (2000)",
      powers: ["Telepathy", "Memory Manipulation", "Mind Control", "Astral Projection"],
      skills: ["Genius-Level Intellect", "Genetics Expert", "Leadership", "Strategy"],
      weapons: ["Cerebro"],
      weakness: "Paralyzed (wheelchair), Physical vulnerability",
      movies: ["X-Men Series", "Doctor Strange in the Multiverse of Madness (Illuminati)"],
      allies: ["X-Men", "Magneto (sometimes)", "Moira MacTaggert"],
      enemies: ["Magneto (sometimes)", "Shadow King", "Sentinels", "Apocalypse"],
      team: "X-Men",
      stats: { strength: 10, intelligence: 98, speed: 10, durability: 20, energy: 95 },
      avatar: "", icon: "🧠"
    },
    {
      id: 32, type: "hero",
      name: "Mystique", realName: "Raven Darkhölme", nickname: "Mystique",
      age: 100, gender: "Female", species: "Mutant",
      status: "Dead", firstAppearance: "X-Men (2000)",
      powers: ["Shapeshifting", "Enhanced Agility", "Decelerated Aging"],
      skills: ["Espionage", "Combat", "Acting", "Infiltration"],
      weapons: [],
      weakness: "True form reveals blue skin, Emotional vulnerabilities",
      movies: ["X-Men Series", "X-Men: First Class", "X-Men: Days of Future Past", "X-Men: Dark Phoenix"],
      allies: ["Magneto", "Professor X", "Brotherhood"],
      enemies: ["Humans", "Sentinels", "William Stryker"],
      team: "Brotherhood of Mutants",
      stats: { strength: 35, intelligence: 70, speed: 50, durability: 40, energy: 15 },
      avatar: "", icon: "🔵"
    },
    {
      id: 33, type: "villain",
      name: "Galactus", realName: "Galan", nickname: "Devourer of Worlds",
      age: "Billions", gender: "Male", species: "Cosmic Entity",
      status: "Alive", firstAppearance: "Fantastic Four: Rise of the Silver Surfer (2007)",
      powers: ["Reality Warping", "Teleportation", "Immortality", "Superhuman Strength", "Levitation", "Force Field", "Healing Factor", "Psychokinesis", "Time Travel", "Telepathy"],
      skills: ["Cosmic Awareness", "Power Cosmic Control"],
      weapons: ["Ultimate Nullifier"],
      weakness: "Cosmic Hunger — must consume planets to survive",
      movies: ["Fantastic Four: Rise of the Silver Surfer", "Fantastic Four: First Steps (upcoming)"],
      allies: ["Silver Surfer", "Heralds of Galactus"],
      enemies: ["Fantastic Four", "Avengers", "All living civilizations"],
      team: "Cosmic Entities",
      stats: { strength: 100, intelligence: 95, speed: 90, durability: 100, energy: 100 },
      avatar: "", icon: "🌍"
    },
    {
      id: 34, type: "hero",
      name: "Mister Fantastic", realName: "Reed Richards", nickname: "Mr. Fantastic",
      age: 42, gender: "Male", species: "Mutate",
      status: "Alive (Multiverse)", firstAppearance: "Fantastic Four (2005)",
      powers: ["Elasticity", "Malleability", "Shape Alteration"],
      skills: ["Genius-Level Intellect", "Physics", "Engineering", "Dimensional Travel"],
      weapons: [],
      weakness: "Extreme temperatures, Vulnerable when stretched thin",
      movies: ["Fantastic Four", "Doctor Strange in the Multiverse of Madness (Illuminati)", "Fantastic Four: First Steps"],
      allies: ["Invisible Woman", "Human Torch", "Thing", "Avengers"],
      enemies: ["Doctor Doom", "Galactus", "Annihilus"],
      team: "Fantastic Four",
      stats: { strength: 30, intelligence: 100, speed: 35, durability: 55, energy: 25 },
      avatar: "", icon: "🔬"
    },
    {
      id: 35, type: "villain",
      name: "Electro", realName: "Maxwell Dillon", nickname: "Electro",
      age: 45, gender: "Male", species: "Mutate",
      status: "Unknown", firstAppearance: "The Amazing Spider-Man 2 (2014)",
      powers: ["Electrokinesis", "Energy Absorption", "Lightning Generation", "Flight (electric form)"],
      skills: ["Electrical Engineering"],
      weapons: [],
      weakness: "Water, Grounding, Rubber insulation",
      movies: ["The Amazing Spider-Man 2", "Spider-Man: No Way Home"],
      allies: ["Sinister Six", "Green Goblin"],
      enemies: ["Spider-Man", "Avengers"],
      team: "Sinister Six",
      stats: { strength: 40, intelligence: 45, speed: 70, durability: 50, energy: 92 },
      avatar: "", icon: "⚡"
    },
    {
      id: 36, type: "hero",
      name: "Colossus", realName: "Piotr Rasputin", nickname: "Colossus",
      age: 30, gender: "Male", species: "Mutant",
      status: "Alive", firstAppearance: "X-Men (2000)",
      powers: ["Organic Steel Transformation", "Superhuman Strength", "Superhuman Durability", "Invulnerability"],
      skills: ["Painting", "Hand-to-Hand Combat"],
      weapons: [],
      weakness: "Heavy weight limits agility, Emotional (family)",
      movies: ["X-Men Series", "Deadpool", "Deadpool 2"],
      allies: ["X-Men", "Deadpool", "Wolverine", "Negasonic Teenage Warhead"],
      enemies: ["Magneto", "Juggernaut", "Sentinels"],
      team: "X-Men",
      stats: { strength: 90, intelligence: 40, speed: 25, durability: 95, energy: 10 },
      avatar: "", icon: "🪨"
    },
    {
      id: 37, type: "villain",
      name: "Juggernaut", realName: "Cain Marko", nickname: "Juggernaut",
      age: 55, gender: "Male", species: "Mutate (Cyttorak-enhanced)",
      status: "Alive", firstAppearance: "X-Men: The Last Stand (2006)",
      powers: ["Superhuman Strength", "Superhuman Durability", "Immortality", "Unstoppable Momentum"],
      skills: ["Brawling", "Military Training"],
      weapons: ["Crimson Gem of Cyttorak (power source)"],
      weakness: "Remove his helmet to expose to telepathy, Must keep moving once started",
      movies: ["X-Men: The Last Stand", "Deadpool 2"],
      allies: ["Brotherhood of Mutants", "Black Tom Cassidy"],
      enemies: ["X-Men", "Professor X (step-brother)", "Deadpool"],
      team: "Brotherhood of Mutants",
      stats: { strength: 97, intelligence: 25, speed: 30, durability: 98, energy: 10 },
      avatar: "", icon: "🔴"
    },
    {
      id: 38, type: "hero",
      name: "Black Cat", realName: "Felicia Hardy", nickname: "Black Cat",
      age: 28, gender: "Female", species: "Mutate",
      status: "Alive", firstAppearance: "Spider-Man PS4 (MCU-adjacent)",
      powers: ["Probability Manipulation (bad luck)", "Enhanced Agility", "Enhanced Reflexes"],
      skills: ["Thievery", "Acrobatics", "Martial Arts", "Stealth"],
      weapons: ["Grappling Hook", "Retractable Claws"],
      weakness: "No superhuman durability, Emotional ties to Spider-Man",
      movies: ["Spider-Man (comics/games universe)"],
      allies: ["Spider-Man", "Silver Sable"],
      enemies: ["Kingpin", "Doctor Octopus"],
      team: "Independent",
      stats: { strength: 30, intelligence: 55, speed: 60, durability: 28, energy: 35 },
      avatar: "", icon: "🐱"
    },
    {
      id: 39, type: "villain",
      name: "Kingpin", realName: "Wilson Fisk", nickname: "The Kingpin of Crime",
      age: 55, gender: "Male", species: "Human",
      status: "Alive", firstAppearance: "Daredevil (2015 — Netflix)",
      powers: [],
      skills: ["Criminal Mastermind", "Hand-to-Hand Combat", "Business Strategy", "Intimidation"],
      weapons: ["Walking Cane (weapon)", "Body Armor Suits"],
      weakness: "Vanessa Marianna (wife), Emotional rage, Arrogance",
      movies: ["Daredevil (Series)", "Hawkeye", "Echo", "Spider-Man: Into the Spider-Verse", "Daredevil: Born Again"],
      allies: ["Bullseye", "Vanessa", "Various crime lords"],
      enemies: ["Daredevil", "Spider-Man", "Punisher", "Jessica Jones", "Kate Bishop"],
      team: "Criminal Underworld",
      stats: { strength: 60, intelligence: 85, speed: 20, durability: 65, energy: 5 },
      avatar: "", icon: "👔"
    }
  ],

  // ──────────────────────────────────────────────
  // MOVIES
  // ──────────────────────────────────────────────
  movies: [
    // Phase 1 — REAL DATA from Kaggle MCU Box Office Dataset
    { id: 1, name: "Iron Man", releaseDate: "2008-05-02", phase: 1, duration: "2h 6m", durationMin: 126, director: "Jon Favreau", producer: "Avi Arad, Kevin Feige", boxOffice: "$585M", worldwideBO: "$585,171,547", domesticBO: "$318,604,126", openingWeekend: "$102,118,668", productionBudget: "$186,000,000", tomatoMeter: 94, audienceScore: 91, imdbRating: 7.9, mainHero: "Iron Man", mainVillain: "Obadiah Stane", summary: "Billionaire Tony Stark builds a high-tech suit of armor after being captured by terrorists, becoming Iron Man.", poster: "🎬" },
    { id: 2, name: "The Incredible Hulk", releaseDate: "2008-06-13", phase: 1, duration: "1h 52m", durationMin: 112, director: "Louis Leterrier", producer: "Avi Arad, Kevin Feige", boxOffice: "$265M", worldwideBO: "$265,573,859", domesticBO: "$134,806,913", openingWeekend: "$55,414,050", productionBudget: "$137,500,000", tomatoMeter: 67, audienceScore: 70, imdbRating: 6.6, mainHero: "Hulk", mainVillain: "Abomination", summary: "Bruce Banner searches for a cure for his gamma radiation condition while being hunted by the military.", poster: "🎬" },
    { id: 3, name: "Iron Man 2", releaseDate: "2010-05-07", phase: 1, duration: "2h 4m", durationMin: 124, director: "Jon Favreau", producer: "Kevin Feige", boxOffice: "$621M", worldwideBO: "$621,156,389", domesticBO: "$312,433,331", openingWeekend: "$128,122,480", productionBudget: "$170,000,000", tomatoMeter: 72, audienceScore: 71, imdbRating: 6.9, mainHero: "Iron Man", mainVillain: "Whiplash", summary: "Tony Stark faces pressure from the government and a vengeful Russian physicist with his own arc reactor technology.", poster: "🎬" },
    { id: 4, name: "Thor", releaseDate: "2011-05-06", phase: 1, duration: "1h 53m", durationMin: 113, director: "Kenneth Branagh", producer: "Kevin Feige", boxOffice: "$449M", worldwideBO: "$449,326,618", domesticBO: "$181,030,624", openingWeekend: "$65,723,338", productionBudget: "$150,000,000", tomatoMeter: 77, audienceScore: 76, imdbRating: 7.0, mainHero: "Thor", mainVillain: "Loki", summary: "The powerful god Thor is cast out of Asgard to Earth, where he must prove himself worthy of his power.", poster: "🎬" },
    { id: 5, name: "Captain America: The First Avenger", releaseDate: "2011-07-22", phase: 1, duration: "2h 4m", durationMin: 124, director: "Joe Johnston", producer: "Kevin Feige", boxOffice: "$370M", worldwideBO: "$370,569,776", domesticBO: "$176,654,505", openingWeekend: "$65,058,524", productionBudget: "$140,000,000", tomatoMeter: 79, audienceScore: 75, imdbRating: 6.9, mainHero: "Captain America", mainVillain: "Red Skull", summary: "Steve Rogers transforms from a frail man into a super soldier to fight Hydra during World War II.", poster: "🎬" },
    { id: 6, name: "The Avengers", releaseDate: "2012-05-04", phase: 1, duration: "2h 23m", durationMin: 143, director: "Joss Whedon", producer: "Kevin Feige", boxOffice: "$1.515B", worldwideBO: "$1,515,100,211", domesticBO: "$623,357,910", openingWeekend: "$207,438,708", productionBudget: "$225,000,000", tomatoMeter: 91, audienceScore: 91, imdbRating: 8.0, mainHero: "Avengers", mainVillain: "Loki", summary: "Earth's mightiest heroes must come together to stop Loki and his alien army from enslaving humanity.", poster: "🎬" },

    // Phase 2
    { id: 7, name: "Iron Man 3", releaseDate: "2013-05-03", phase: 2, duration: "2h 10m", durationMin: 130, director: "Shane Black", producer: "Kevin Feige", boxOffice: "$1.215B", worldwideBO: "$1,215,392,272", domesticBO: "$408,992,272", openingWeekend: "$174,144,585", productionBudget: "$200,000,000", tomatoMeter: 79, audienceScore: 78, imdbRating: 7.1, mainHero: "Iron Man", mainVillain: "Mandarin / Aldrich Killian", summary: "Tony Stark faces PTSD and a powerful new enemy who threatens to destroy everything he holds dear.", poster: "🎬" },
    { id: 8, name: "Thor: The Dark World", releaseDate: "2013-11-08", phase: 2, duration: "1h 51m", durationMin: 111, director: "Alan Taylor", producer: "Kevin Feige", boxOffice: "$644M", worldwideBO: "$644,602,516", domesticBO: "$206,362,140", openingWeekend: "$85,737,841", productionBudget: "$150,000,000", tomatoMeter: 66, audienceScore: 75, imdbRating: 6.8, mainHero: "Thor", mainVillain: "Malekith", summary: "Thor battles the Dark Elves led by Malekith who seek to plunge the universe into eternal darkness.", poster: "🎬" },
    { id: 9, name: "Captain America: The Winter Soldier", releaseDate: "2014-04-04", phase: 2, duration: "2h 15m", durationMin: 135, director: "Russo Brothers", producer: "Kevin Feige", boxOffice: "$714M", worldwideBO: "$714,401,889", domesticBO: "$259,746,958", openingWeekend: "$95,023,721", productionBudget: "$170,000,000", tomatoMeter: 90, audienceScore: 92, imdbRating: 7.7, mainHero: "Captain America", mainVillain: "Winter Soldier / Hydra", summary: "Steve Rogers uncovers a conspiracy within S.H.I.E.L.D. while facing a mysterious assassin from his past.", poster: "🎬" },
    { id: 10, name: "Guardians of the Galaxy", releaseDate: "2014-08-01", phase: 2, duration: "2h 1m", durationMin: 121, director: "James Gunn", producer: "Kevin Feige", boxOffice: "$770M", worldwideBO: "$770,882,395", domesticBO: "$333,714,112", openingWeekend: "$94,320,883", productionBudget: "$170,000,000", tomatoMeter: 92, audienceScore: 92, imdbRating: 8.0, mainHero: "Star-Lord", mainVillain: "Ronan the Accuser", summary: "A group of intergalactic misfits band together to stop a powerful villain from destroying the galaxy.", poster: "🎬" },
    { id: 11, name: "Avengers: Age of Ultron", releaseDate: "2015-05-01", phase: 2, duration: "2h 21m", durationMin: 141, director: "Joss Whedon", producer: "Kevin Feige", boxOffice: "$1.395B", worldwideBO: "$1,395,316,979", domesticBO: "$459,005,868", openingWeekend: "$191,271,109", productionBudget: "$365,000,000", tomatoMeter: 76, audienceScore: 83, imdbRating: 7.3, mainHero: "Avengers", mainVillain: "Ultron", summary: "The Avengers must stop Ultron, a sentient AI created by Tony Stark, from destroying humanity.", poster: "🎬" },
    { id: 12, name: "Ant-Man", releaseDate: "2015-07-17", phase: 2, duration: "1h 57m", durationMin: 117, director: "Peyton Reed", producer: "Kevin Feige", boxOffice: "$518M", worldwideBO: "$518,858,449", domesticBO: "$180,202,163", openingWeekend: "$57,225,526", productionBudget: "$130,000,000", tomatoMeter: 83, audienceScore: 85, imdbRating: 7.3, mainHero: "Ant-Man", mainVillain: "Yellowjacket", summary: "A master thief is recruited to wear a suit that shrinks him to ant-size and gives him superhuman strength.", poster: "🎬" },

    // Phase 3
    { id: 13, name: "Captain America: Civil War", releaseDate: "2016-05-06", phase: 3, duration: "2h 26m", durationMin: 146, director: "Russo Brothers", producer: "Kevin Feige", boxOffice: "$1.151B", worldwideBO: "$1,151,918,521", domesticBO: "$408,084,349", openingWeekend: "$179,139,142", productionBudget: "$250,000,000", tomatoMeter: 90, audienceScore: 89, imdbRating: 7.8, mainHero: "Captain America / Iron Man", mainVillain: "Zemo", summary: "The Avengers split into opposing factions over government oversight, leading to an epic battle.", poster: "🎬" },
    { id: 14, name: "Doctor Strange", releaseDate: "2016-11-04", phase: 3, duration: "1h 55m", durationMin: 115, director: "Scott Derrickson", producer: "Kevin Feige", boxOffice: "$676M", worldwideBO: "$676,354,481", domesticBO: "$232,641,920", openingWeekend: "$85,058,311", productionBudget: "$165,000,000", tomatoMeter: 89, audienceScore: 86, imdbRating: 7.5, mainHero: "Doctor Strange", mainVillain: "Kaecilius / Dormammu", summary: "A brilliant surgeon discovers the world of mystic arts after a car accident destroys his career.", poster: "🎬" },
    { id: 15, name: "Guardians of the Galaxy Vol. 2", releaseDate: "2017-05-05", phase: 3, duration: "2h 15m", durationMin: 135, director: "James Gunn", producer: "Kevin Feige", boxOffice: "$869M", worldwideBO: "$869,113,101", domesticBO: "$389,813,101", openingWeekend: "$146,510,104", productionBudget: "$200,000,000", tomatoMeter: 85, audienceScore: 87, imdbRating: 7.6, mainHero: "Star-Lord", mainVillain: "Ego the Living Planet", summary: "The Guardians travel across the cosmos as Peter Quill learns the truth about his mysterious parentage.", poster: "🎬" },
    { id: 16, name: "Spider-Man: Homecoming", releaseDate: "2017-07-07", phase: 3, duration: "2h 13m", durationMin: 133, director: "Jon Watts", producer: "Kevin Feige, Amy Pascal", boxOffice: "$878M", worldwideBO: "$878,346,440", domesticBO: "$334,201,140", openingWeekend: "$117,027,503", productionBudget: "$175,000,000", tomatoMeter: 92, audienceScore: 87, imdbRating: 7.4, mainHero: "Spider-Man", mainVillain: "Vulture", summary: "Peter Parker balances high school life with being Spider-Man while facing the dangerous Vulture.", poster: "🎬" },
    { id: 17, name: "Thor: Ragnarok", releaseDate: "2017-11-03", phase: 3, duration: "2h 10m", durationMin: 130, director: "Taika Waititi", producer: "Kevin Feige", boxOffice: "$850M", worldwideBO: "$850,482,778", domesticBO: "$315,058,289", openingWeekend: "$122,744,989", productionBudget: "$180,000,000", tomatoMeter: 93, audienceScore: 87, imdbRating: 7.9, mainHero: "Thor", mainVillain: "Hela", summary: "Thor must escape gladiatorial combat and save Asgard from the all-powerful Hela.", poster: "🎬" },
    { id: 18, name: "Black Panther", releaseDate: "2018-02-16", phase: 3, duration: "2h 14m", durationMin: 134, director: "Ryan Coogler", producer: "Kevin Feige", boxOffice: "$1.336B", worldwideBO: "$1,336,494,321", domesticBO: "$700,059,566", openingWeekend: "$202,003,951", productionBudget: "$200,000,000", tomatoMeter: 96, audienceScore: 79, imdbRating: 7.3, mainHero: "Black Panther", mainVillain: "Killmonger", summary: "T'Challa returns to Wakanda to take the throne but faces a challenger with a vendetta against the kingdom.", poster: "🎬" },
    { id: 19, name: "Avengers: Infinity War", releaseDate: "2018-04-27", phase: 3, duration: "2h 29m", durationMin: 149, director: "Russo Brothers", producer: "Kevin Feige", boxOffice: "$2.048B", worldwideBO: "$2,048,359,754", domesticBO: "$678,815,482", openingWeekend: "$257,698,183", productionBudget: "$300,000,000", tomatoMeter: 85, audienceScore: 91, imdbRating: 8.4, mainHero: "Avengers", mainVillain: "Thanos", summary: "The Avengers and their allies must sacrifice everything to stop Thanos from collecting the Infinity Stones.", poster: "🎬" },
    { id: 20, name: "Ant-Man and the Wasp", releaseDate: "2018-07-06", phase: 3, duration: "1h 58m", durationMin: 118, director: "Peyton Reed", producer: "Kevin Feige", boxOffice: "$623M", worldwideBO: "$623,144,660", domesticBO: "$216,648,740", openingWeekend: "$75,812,205", productionBudget: "$130,000,000", tomatoMeter: 87, audienceScore: 81, imdbRating: 7.0, mainHero: "Ant-Man", mainVillain: "Ghost", summary: "Scott Lang partners with Hope van Dyne to uncover secrets from the Quantum Realm.", poster: "🎬" },
    { id: 21, name: "Captain Marvel", releaseDate: "2019-03-08", phase: 3, duration: "2h 4m", durationMin: 124, director: "Anna Boden, Ryan Fleck", producer: "Kevin Feige", boxOffice: "$1.129B", worldwideBO: "$1,129,727,388", domesticBO: "$426,829,839", openingWeekend: "$153,433,423", productionBudget: "$175,000,000", tomatoMeter: 79, audienceScore: 45, imdbRating: 6.8, mainHero: "Captain Marvel", mainVillain: "Yon-Rogg", summary: "Carol Danvers discovers her true identity and incredible powers as she fights an intergalactic war.", poster: "🎬" },
    { id: 22, name: "Avengers: Endgame", releaseDate: "2019-04-26", phase: 3, duration: "3h 1m", durationMin: 181, director: "Russo Brothers", producer: "Kevin Feige", boxOffice: "$2.797B", worldwideBO: "$2,797,800,564", domesticBO: "$858,373,000", openingWeekend: "$357,115,007", productionBudget: "$400,000,000", tomatoMeter: 94, audienceScore: 90, imdbRating: 8.4, mainHero: "Avengers", mainVillain: "Thanos", summary: "The remaining Avengers devise a desperate plan to undo Thanos' snap and restore the universe.", poster: "🎬" },
    { id: 23, name: "Spider-Man: Far From Home", releaseDate: "2019-07-02", phase: 3, duration: "2h 9m", durationMin: 129, director: "Jon Watts", producer: "Kevin Feige, Amy Pascal", boxOffice: "$1.132B", worldwideBO: "$1,132,532,832", domesticBO: "$390,532,085", openingWeekend: "$92,579,212", productionBudget: "$160,000,000", tomatoMeter: 90, audienceScore: 95, imdbRating: 7.4, mainHero: "Spider-Man", mainVillain: "Mysterio", summary: "Peter Parker goes on a European vacation but must step up when elemental creatures threaten the continent.", poster: "🎬" },

    // Phase 4 — REAL DATA
    { id: 24, name: "Black Widow", releaseDate: "2021-07-09", phase: 4, duration: "2h 13m", durationMin: 133, director: "Cate Shortland", producer: "Kevin Feige", boxOffice: "$379M", worldwideBO: "$379,751,655", domesticBO: "$183,651,655", openingWeekend: "$80,366,312", productionBudget: "$200,000,000", tomatoMeter: 79, audienceScore: 91, imdbRating: 6.7, mainHero: "Black Widow", mainVillain: "Taskmaster / Dreykov", summary: "Natasha Romanoff confronts her past and the dark legacy of the Red Room.", poster: "🎬" },
    { id: 25, name: "Shang-Chi and the Legend of the Ten Rings", releaseDate: "2021-09-03", phase: 4, duration: "2h 13m", durationMin: 133, director: "Destin Daniel Cretton", producer: "Kevin Feige", boxOffice: "$432M", worldwideBO: "$432,243,292", domesticBO: "$224,543,292", openingWeekend: "$75,388,688", productionBudget: "$150,000,000", tomatoMeter: 91, audienceScore: 98, imdbRating: 7.4, mainHero: "Shang-Chi", mainVillain: "Wenwu / Dweller-in-Darkness", summary: "Shang-Chi must confront his past when his father draws him into the Ten Rings organization.", poster: "🎬" },
    { id: 26, name: "Eternals", releaseDate: "2021-11-05", phase: 4, duration: "2h 37m", durationMin: 157, director: "Chloé Zhao", producer: "Kevin Feige", boxOffice: "$402M", worldwideBO: "$402,064,929", domesticBO: "$164,870,264", openingWeekend: "$71,297,219", productionBudget: "$200,000,000", tomatoMeter: 47, audienceScore: 78, imdbRating: 6.3, mainHero: "Eternals", mainVillain: "Deviants / Arishem", summary: "An immortal alien race emerges from hiding to protect Earth from their ancient counterparts, the Deviants.", poster: "🎬" },
    { id: 27, name: "Spider-Man: No Way Home", releaseDate: "2021-12-17", phase: 4, duration: "2h 28m", durationMin: 148, director: "Jon Watts", producer: "Kevin Feige, Amy Pascal", boxOffice: "$1.891B", worldwideBO: "$1,891,108,035", domesticBO: "$803,975,784", openingWeekend: "$260,138,569", productionBudget: "$200,000,000", tomatoMeter: 93, audienceScore: 98, imdbRating: 8.2, mainHero: "Spider-Man", mainVillain: "Green Goblin / Multiverse Villains", summary: "Peter Parker asks Doctor Strange to make the world forget his identity, but the spell goes wrong.", poster: "🎬" },
    { id: 28, name: "Doctor Strange in the Multiverse of Madness", releaseDate: "2022-05-06", phase: 4, duration: "2h 6m", durationMin: 126, director: "Sam Raimi", producer: "Kevin Feige", boxOffice: "$956M", worldwideBO: "$955,775,804", domesticBO: "$411,331,607", openingWeekend: "$187,420,998", productionBudget: "$200,000,000", tomatoMeter: 74, audienceScore: 85, imdbRating: 6.9, mainHero: "Doctor Strange", mainVillain: "Scarlet Witch", summary: "Doctor Strange traverses the multiverse to protect a teenager with the power to travel between realities.", poster: "🎬" },
    { id: 29, name: "Thor: Love and Thunder", releaseDate: "2022-07-08", phase: 4, duration: "1h 58m", durationMin: 118, director: "Taika Waititi", producer: "Kevin Feige", boxOffice: "$761M", worldwideBO: "$760,928,081", domesticBO: "$343,256,830", openingWeekend: "$144,165,107", productionBudget: "$250,000,000", tomatoMeter: 63, audienceScore: 77, imdbRating: 6.2, mainHero: "Thor", mainVillain: "Gorr the God Butcher", summary: "Thor enlists Valkyrie, Korg, and Jane Foster to fight Gorr, who seeks to eliminate all gods.", poster: "🎬" },
    { id: 30, name: "Black Panther: Wakanda Forever", releaseDate: "2022-11-11", phase: 4, duration: "2h 41m", durationMin: 161, director: "Ryan Coogler", producer: "Kevin Feige", boxOffice: "$859M", worldwideBO: "$859,208,836", domesticBO: "$453,829,060", openingWeekend: "$181,339,761", productionBudget: "$250,000,000", tomatoMeter: 84, audienceScore: 94, imdbRating: 6.7, mainHero: "Shuri / Black Panther", mainVillain: "Namor", summary: "Wakanda mourns King T'Challa while facing a new threat from the underwater kingdom of Talokan.", poster: "🎬" },

    // Phase 5
    { id: 31, name: "Ant-Man and the Wasp: Quantumania", releaseDate: "2023-02-17", phase: 5, duration: "2h 5m", durationMin: 125, director: "Peyton Reed", producer: "Kevin Feige", boxOffice: "$476M", worldwideBO: "$476,071,180", domesticBO: "$214,504,909", openingWeekend: "$106,109,650", productionBudget: "$200,000,000", tomatoMeter: 46, audienceScore: 83, imdbRating: 6.0, mainHero: "Ant-Man", mainVillain: "Kang the Conqueror", summary: "The Ant-Man family gets sucked into the Quantum Realm and faces Kang the Conqueror.", poster: "🎬" },
    { id: 32, name: "Guardians of the Galaxy Vol. 3", releaseDate: "2023-05-05", phase: 5, duration: "2h 30m", durationMin: 150, director: "James Gunn", producer: "Kevin Feige", boxOffice: "$845M", worldwideBO: "$845,555,777", domesticBO: "$358,995,815", openingWeekend: "$118,414,021", productionBudget: "$250,000,000", tomatoMeter: 82, audienceScore: 95, imdbRating: 7.9, mainHero: "Star-Lord", mainVillain: "High Evolutionary", summary: "The Guardians embark on a mission to save Rocket and face the High Evolutionary.", poster: "🎬" },
    { id: 33, name: "The Marvels", releaseDate: "2023-11-10", phase: 5, duration: "1h 45m", durationMin: 105, director: "Nia DaCosta", producer: "Kevin Feige", boxOffice: "$206M", worldwideBO: "$206,128,076", domesticBO: "$84,500,479", openingWeekend: "$46,110,859", productionBudget: "$220,000,000", tomatoMeter: 62, audienceScore: 75, imdbRating: 5.5, mainHero: "Captain Marvel", mainVillain: "Dar-Benn", summary: "Captain Marvel, Ms. Marvel, and Monica Rambeau must work together when their powers become entangled.", poster: "🎬" }
  ],

  // ──────────────────────────────────────────────
  // ACTORS
  // ──────────────────────────────────────────────
  actors: [
    { id: 1, name: "Robert Downey Jr.", dob: "1965-04-04", age: 60, nationality: "American", character: "Iron Man / Tony Stark", yearsActive: "2008–2019", otherMovies: ["Sherlock Holmes", "Oppenheimer", "Chaplin", "The Judge"], avatar: "🎭" },
    { id: 2, name: "Chris Evans", dob: "1981-06-13", age: 44, nationality: "American", character: "Captain America / Steve Rogers", yearsActive: "2011–2019", otherMovies: ["Knives Out", "The Gray Man", "Snowpiercer", "Gifted"], avatar: "🎭" },
    { id: 3, name: "Chris Hemsworth", dob: "1983-08-11", age: 42, nationality: "Australian", character: "Thor", yearsActive: "2011–2022", otherMovies: ["Extraction", "Rush", "Furiosa", "Men in Black: International"], avatar: "🎭" },
    { id: 4, name: "Scarlett Johansson", dob: "1984-11-22", age: 41, nationality: "American", character: "Black Widow / Natasha Romanoff", yearsActive: "2010–2021", otherMovies: ["Lucy", "Marriage Story", "Jojo Rabbit", "Lost in Translation"], avatar: "🎭" },
    { id: 5, name: "Mark Ruffalo", dob: "1967-11-22", age: 58, nationality: "American", character: "Hulk / Bruce Banner", yearsActive: "2012–Present", otherMovies: ["Spotlight", "Shutter Island", "Foxcatcher", "Dark Waters"], avatar: "🎭" },
    { id: 6, name: "Tom Holland", dob: "1996-06-01", age: 29, nationality: "British", character: "Spider-Man / Peter Parker", yearsActive: "2016–2021", otherMovies: ["Uncharted", "The Impossible", "Cherry", "The Devil All the Time"], avatar: "🎭" },
    { id: 7, name: "Benedict Cumberbatch", dob: "1976-07-19", age: 49, nationality: "British", character: "Doctor Strange / Stephen Strange", yearsActive: "2016–2022", otherMovies: ["Sherlock", "The Imitation Game", "1917", "The Power of the Dog"], avatar: "🎭" },
    { id: 8, name: "Chadwick Boseman", dob: "1976-11-29", age: "43 (deceased)", nationality: "American", character: "Black Panther / T'Challa", yearsActive: "2016–2019", otherMovies: ["42", "Marshall", "Da 5 Bloods", "Ma Rainey's Black Bottom"], avatar: "🎭" },
    { id: 9, name: "Josh Brolin", dob: "1968-02-12", age: 58, nationality: "American", character: "Thanos", yearsActive: "2014–2019", otherMovies: ["No Country for Old Men", "Sicario", "Dune", "Milk"], avatar: "🎭" },
    { id: 10, name: "Tom Hiddleston", dob: "1981-02-09", age: 45, nationality: "British", character: "Loki", yearsActive: "2011–Present", otherMovies: ["The Night Manager", "Kong: Skull Island", "Crimson Peak", "High-Rise"], avatar: "🎭" },
    { id: 11, name: "Chris Pratt", dob: "1979-06-21", age: 46, nationality: "American", character: "Star-Lord / Peter Quill", yearsActive: "2014–2023", otherMovies: ["Jurassic World", "The Lego Movie", "Passengers", "The Tomorrow War"], avatar: "🎭" },
    { id: 12, name: "Elizabeth Olsen", dob: "1989-02-16", age: 37, nationality: "American", character: "Scarlet Witch / Wanda Maximoff", yearsActive: "2015–2022", otherMovies: ["Wind River", "Sorry for Your Loss", "Martha Marcy May Marlene", "Oldboy"], avatar: "🎭" },
    { id: 13, name: "Paul Rudd", dob: "1969-04-06", age: 56, nationality: "American", character: "Ant-Man / Scott Lang", yearsActive: "2015–2023", otherMovies: ["Clueless", "Anchorman", "I Love You, Man", "Living with Yourself"], avatar: "🎭" },
    { id: 14, name: "Brie Larson", dob: "1989-10-01", age: 36, nationality: "American", character: "Captain Marvel / Carol Danvers", yearsActive: "2019–2023", otherMovies: ["Room", "Short Term 12", "Kong: Skull Island", "Just Mercy"], avatar: "🎭" },
    { id: 15, name: "Samuel L. Jackson", dob: "1948-12-21", age: 77, nationality: "American", character: "Nick Fury", yearsActive: "2008–Present", otherMovies: ["Pulp Fiction", "Django Unchained", "The Hateful Eight", "Glass"], avatar: "🎭" }
  ],

  // ──────────────────────────────────────────────
  // TEAMS / ORGANIZATIONS
  // ──────────────────────────────────────────────
  teams: [
    { id: 1, name: "Avengers", leader: "Nick Fury / Captain America / Iron Man", members: ["Iron Man", "Captain America", "Thor", "Hulk", "Black Widow", "Hawkeye", "Scarlet Witch", "Vision", "Spider-Man", "War Machine", "Falcon", "Ant-Man", "Captain Marvel", "Black Panther", "Doctor Strange"], firstAppearance: "The Avengers (2012)", enemies: ["Loki", "Ultron", "Thanos"], base: "Avengers Tower / Avengers Compound, New York", icon: "🅰️" },
    { id: 2, name: "Guardians of the Galaxy", leader: "Star-Lord", members: ["Star-Lord", "Gamora", "Rocket Raccoon", "Groot", "Drax", "Mantis", "Nebula", "Adam Warlock"], firstAppearance: "Guardians of the Galaxy (2014)", enemies: ["Ronan", "Ego", "Thanos", "High Evolutionary"], base: "The Milano / Knowhere", icon: "🚀" },
    { id: 3, name: "S.H.I.E.L.D.", leader: "Nick Fury", members: ["Nick Fury", "Maria Hill", "Phil Coulson", "Black Widow", "Hawkeye", "Agent 13"], firstAppearance: "Iron Man (2008)", enemies: ["Hydra", "A.I.M."], base: "The Triskelion, Washington D.C. / Helicarrier", icon: "🦅" },
    { id: 4, name: "Hydra", leader: "Red Skull / Alexander Pierce / Baron Strucker", members: ["Red Skull", "Arnim Zola", "Brock Rumlow", "Winter Soldier (brainwashed)", "Baron Strucker"], firstAppearance: "Captain America: The First Avenger (2011)", enemies: ["S.H.I.E.L.D.", "Captain America", "Avengers"], base: "Various Secret Bases Worldwide", icon: "🐙" },
    { id: 5, name: "Wakanda", leader: "T'Challa / Shuri", members: ["T'Challa", "Shuri", "Okoye", "Nakia", "M'Baku", "Ayo"], firstAppearance: "Black Panther (2018)", enemies: ["Killmonger", "Klaue", "Namor"], base: "Wakanda, East Africa", icon: "🏔️" },
    { id: 6, name: "Black Order", leader: "Thanos", members: ["Ebony Maw", "Cull Obsidian", "Proxima Midnight", "Corvus Glaive"], firstAppearance: "Avengers: Infinity War (2018)", enemies: ["Avengers", "Guardians of the Galaxy"], base: "Sanctuary II (Thanos' Ship)", icon: "⚫" },
    { id: 7, name: "Masters of the Mystic Arts", leader: "Ancient One / Doctor Strange", members: ["Doctor Strange", "Wong", "Ancient One", "Mordo (formerly)"], firstAppearance: "Doctor Strange (2016)", enemies: ["Dormammu", "Kaecilius"], base: "Kamar-Taj, Nepal / Sanctum Sanctorum, New York", icon: "🔮" },
    { id: 8, name: "Ravagers", leader: "Yondu Udonta / Stakar Ogord", members: ["Yondu", "Kraglin", "Star-Lord (formerly)"], firstAppearance: "Guardians of the Galaxy (2014)", enemies: ["Kree Empire"], base: "Various Ships", icon: "🏴‍☠️" }
  ],

  // ──────────────────────────────────────────────
  // TIMELINE / PHASES
  // ──────────────────────────────────────────────
  phases: [
    { id: 1, name: "Phase 1 — The Infinity Saga Begins", years: "2008–2012", description: "Introduction of core Avengers members and the formation of the team.", movieCount: 6, keyEvent: "Battle of New York", color: "#e74c3c" },
    { id: 2, name: "Phase 2 — New Heroes Rise", years: "2013–2015", description: "Expansion of the MCU with new heroes and cosmic threats.", movieCount: 6, keyEvent: "Fall of S.H.I.E.L.D. & Age of Ultron", color: "#3498db" },
    { id: 3, name: "Phase 3 — Infinity War & Endgame", years: "2016–2019", description: "The Infinity Saga culminates in the epic battle against Thanos.", movieCount: 11, keyEvent: "The Snap & Time Heist", color: "#9b59b6" },
    { id: 4, name: "Phase 4 — The Multiverse Saga", years: "2021–2022", description: "New heroes emerge and the multiverse concept is introduced.", movieCount: 7, keyEvent: "Multiverse Opens", color: "#2ecc71" },
    { id: 5, name: "Phase 5 — Kang Dynasty", years: "2023–2024", description: "The threat of Kang the Conqueror looms over the multiverse.", movieCount: 3, keyEvent: "Kang Dynasty Begins", color: "#f39c12" }
  ],

  // ──────────────────────────────────────────────
  // RELATIONSHIPS (for graph visualization)
  // ──────────────────────────────────────────────
  relationships: [
    { from: "Iron Man", to: "Captain America", type: "Friend / Rival" },
    { from: "Iron Man", to: "Spider-Man", type: "Mentor" },
    { from: "Iron Man", to: "Pepper Potts", type: "Love Interest" },
    { from: "Iron Man", to: "War Machine", type: "Best Friend" },
    { from: "Iron Man", to: "Thanos", type: "Enemy" },
    { from: "Captain America", to: "Falcon", type: "Successor" },
    { from: "Captain America", to: "Red Skull", type: "Enemy" },
    { from: "Thor", to: "Loki", type: "Brother / Rival" },
    { from: "Thor", to: "Hela", type: "Enemy (Sister)" },
    { from: "Hulk", to: "Black Widow", type: "Love Interest" },
    { from: "Thanos", to: "Avengers", type: "Enemy" },
    { from: "Thanos", to: "Black Order", type: "Leader" },
    { from: "Scarlet Witch", to: "Vision", type: "Love Interest" },
    { from: "Scarlet Witch", to: "Thanos", type: "Enemy" },
    { from: "Star-Lord", to: "Gamora", type: "Love Interest" },
    { from: "Doctor Strange", to: "Dormammu", type: "Enemy" },
    { from: "Black Panther", to: "Killmonger", type: "Enemy (Cousin)" },
    { from: "Nick Fury", to: "Avengers", type: "Founder" },
    { from: "Loki", to: "Thor", type: "Brother" },
    { from: "Kang the Conqueror", to: "Ant-Man", type: "Enemy" }
  ],

  // ──────────────────────────────────────────────
  // UNIVERSE / MULTIVERSE DATA
  // ──────────────────────────────────────────────
  universeData: {
    "Iron Man":          { universe: "Earth-199999", variant: false },
    "Captain America":   { universe: "Earth-199999", variant: false },
    "Thor":              { universe: "Earth-199999", variant: false },
    "Hulk":              { universe: "Earth-199999", variant: false },
    "Black Widow":       { universe: "Earth-199999", variant: false },
    "Spider-Man":        { universe: "Earth-199999", variant: false, variantNote: "Interacted with Earth-96283 & Earth-120703 Spider-Men in No Way Home" },
    "Doctor Strange":    { universe: "Earth-199999", variant: true, variantNote: "Sinister Strange & Defender Strange variants exist across the Multiverse" },
    "Black Panther":     { universe: "Earth-199999", variant: false },
    "Scarlet Witch":     { universe: "Earth-199999", variant: true, variantNote: "Earth-838 variant killed by main Wanda in Multiverse of Madness" },
    "Star-Lord":         { universe: "Earth-199999", variant: false },
    "Ant-Man":           { universe: "Earth-199999", variant: false },
    "Captain Marvel":    { universe: "Earth-199999", variant: false },
    "Thanos":            { universe: "Earth-199999", variant: false, variantNote: "2014 variant traveled to 2023 in Endgame" },
    "Loki":              { universe: "Earth-199999", variant: true, variantNote: "Sacred Timeline Loki died; TVA Variant (Loki Series) exists across timelines — Sylvie is a female variant" },
    "Ultron":            { universe: "Earth-199999", variant: true, variantNote: "Ultron Infinity variant conquered his universe in What If...?" },
    "Hela":              { universe: "Earth-199999", variant: false },
    "Killmonger":        { universe: "Earth-199999", variant: true, variantNote: "What If...? variant became Black Panther & betrayed Tony Stark" },
    "Kang the Conqueror":{ universe: "Earth-Unknown", variant: true, variantNote: "Infinite Kang variants exist — He Who Remains, Rama-Tut, Immortus, etc." },
    "Red Skull":         { universe: "Earth-199999", variant: false },
    "Nick Fury":         { universe: "Earth-199999", variant: false },
    "Pepper Potts":      { universe: "Earth-199999", variant: false },
    "War Machine":       { universe: "Earth-199999", variant: false },
    "Falcon":            { universe: "Earth-199999", variant: false },
    "Vision":            { universe: "Earth-199999", variant: true, variantNote: "White Vision rebuilt from original body with restored memories" },
    // NEW — From Kaggle Marvel Characters Dataset
    "Deadpool":          { universe: "Earth-10005 → Earth-616", variant: true, variantNote: "Originally from X-Men universe, crossed into MCU via multiverse in Deadpool & Wolverine" },
    "Daredevil":         { universe: "Earth-199999", variant: false, variantNote: "Netflix Daredevil confirmed canon in the MCU Sacred Timeline" },
    "Jessica Jones":     { universe: "Earth-199999", variant: false, variantNote: "Netflix Defender confirmed part of MCU Sacred Timeline" },
    "Abomination":       { universe: "Earth-199999", variant: false },
    "Storm":             { universe: "Earth-10005", variant: false, variantNote: "X-Men timeline — may appear in MCU via multiverse integration" },
    "Magneto":           { universe: "Earth-10005 / Earth-616", variant: true, variantNote: "Multiple variants: Ian McKellen (original), Michael Fassbender (First Class)" },
    "Professor X":       { universe: "Earth-838", variant: true, variantNote: "Earth-838 Illuminati variant killed by Scarlet Witch in Multiverse of Madness" },
    "Mystique":          { universe: "Earth-10005", variant: false, variantNote: "X-Men timeline — Raven Darkhölme" },
    "Galactus":          { universe: "Earth-616 (Cosmic)", variant: false, variantNote: "Devourer of Worlds — to appear in Fantastic Four: First Steps" },
    "Mister Fantastic":  { universe: "Earth-838 / Earth-616", variant: true, variantNote: "Earth-838 variant killed by Wanda; Earth-616 variant in Fantastic Four: First Steps" },
    "Electro":           { universe: "Earth-120703", variant: true, variantNote: "Pulled from Amazing Spider-Man universe into MCU in No Way Home" },
    "Colossus":          { universe: "Earth-10005", variant: false, variantNote: "X-Men/Deadpool timeline" },
    "Juggernaut":        { universe: "Earth-10005", variant: false },
    "Black Cat":         { universe: "Earth-616", variant: false },
    "Kingpin":           { universe: "Earth-199999", variant: false, variantNote: "Netflix villain confirmed MCU canon — appeared in Hawkeye & Echo" }
  },

  // ──────────────────────────────────────────────
  // MCU QUIZ QUESTIONS
  // ──────────────────────────────────────────────
  quizQuestions: [
    { id:1,  question:"Who said 'I am Iron Man' at the end of the first MCU film?", options:["Steve Rogers","Tony Stark","Nick Fury","Bruce Banner"], correct:1, difficulty:"easy" },
    { id:2,  question:"Which Infinity Stone was hidden on Vormir?", options:["Time Stone","Mind Stone","Soul Stone","Power Stone"], correct:2, difficulty:"medium" },
    { id:3,  question:"What is Thor's hammer called?", options:["Stormbreaker","Gungnir","Mjolnir","Hofund"], correct:2, difficulty:"easy" },
    { id:4,  question:"Who snapped the Infinity Gauntlet to bring everyone back in Endgame?", options:["Iron Man","Hulk","Thor","Captain Marvel"], correct:1, difficulty:"medium" },
    { id:5,  question:"What is the name of Black Panther's country?", options:["Sokovia","Wakanda","Asgard","Kamar-Taj"], correct:1, difficulty:"easy" },
    { id:6,  question:"Which MCU movie grossed the highest worldwide?", options:["Avengers: Infinity War","Avengers: Endgame","Spider-Man: No Way Home","Black Panther"], correct:1, difficulty:"medium" },
    { id:7,  question:"Who is the Sorcerer Supreme after the Ancient One?", options:["Wong","Doctor Strange","Mordo","Wanda"], correct:0, difficulty:"hard" },
    { id:8,  question:"What metal is Captain America's shield made of?", options:["Adamantium","Uru","Vibranium","Titanium"], correct:2, difficulty:"easy" },
    { id:9,  question:"Which character collected all six Infinity Stones first?", options:["Iron Man","Thanos","Doctor Strange","Vision"], correct:1, difficulty:"easy" },
    { id:10, question:"Who is Peter Quill's father?", options:["Yondu","Ego","Thanos","Odin"], correct:1, difficulty:"medium" },
    { id:11, question:"What organization did Hydra secretly infiltrate for decades?", options:["Stark Industries","S.H.I.E.L.D.","NASA","CIA"], correct:1, difficulty:"easy" },
    { id:12, question:"Which MCU Phase introduced the Multiverse concept?", options:["Phase 2","Phase 3","Phase 4","Phase 5"], correct:2, difficulty:"medium" },
    { id:13, question:"Who destroyed Asgard in Thor: Ragnarok?", options:["Thor","Hela","Surtur","Loki"], correct:2, difficulty:"medium" },
    { id:14, question:"What is Thanos' home planet called?", options:["Xandar","Titan","Knowhere","Sakaar"], correct:1, difficulty:"medium" },
    { id:15, question:"Who lifted Mjolnir during the final battle in Endgame?", options:["Thor only","Captain America","Spider-Man","Hulk"], correct:1, difficulty:"easy" },
    { id:16, question:"How many Infinity Stones exist?", options:["4","5","6","8"], correct:2, difficulty:"easy" },
    { id:17, question:"Who directed Avengers: Endgame?", options:["Joss Whedon","Taika Waititi","Russo Brothers","Jon Favreau"], correct:2, difficulty:"medium" },
    { id:18, question:"What is the name of Thanos' army's warship?", options:["The Milano","Sanctuary II","Dark Aster","Benatar"], correct:1, difficulty:"hard" },
    { id:19, question:"Which character said 'I can do this all day'?", options:["Iron Man","Thor","Captain America","Spider-Man"], correct:2, difficulty:"easy" },
    { id:20, question:"What does TVA stand for in the Loki series?", options:["Time Variance Authority","Temporal Void Agency","Timeline Verification Authority","Time Variant Association"], correct:0, difficulty:"hard" }
  ]
};
